// Every permission key in the system
export const PERMISSION_KEYS = [
  "analytics.dashboard",
  "analytics.export",
  "analytics.reports",
  "appointments.view",
  "appointments.create",
  "appointments.edit",
  "appointments.delete",
  "appointments.assign",
  "appointments.reschedule",
  "appointments.cancel",
  "appointments.export",
  "patients.view",
  "patients.create",
  "patients.edit",
  "patients.delete",
  "patients.export",
  "billing.view",
  "billing.create",
  "billing.edit",
  "billing.delete",
  "billing.export",
  "medical_records.view",
  "medical_records.create",
  "medical_records.edit",
  "medical_records.delete",
  "prescriptions.view",
  "prescriptions.create",
  "prescriptions.edit",
  "prescriptions.delete",
  "test_reports.view",
  "test_reports.create",
  "test_reports.edit",
  "test_reports.delete",
  "inventory.view",
  "inventory.create",
  "inventory.edit",
  "inventory.delete",
  "staff.view",
  "staff.create",
  "staff.edit",
  "staff.delete",
  "services.view",
  "services.create",
  "services.edit",
  "services.delete",
  "departments.view",
  "departments.create",
  "departments.edit",
  "departments.delete",
  "settings.view",
  "settings.edit",
  "odontogram.view",
  "odontogram.create",
  "odontogram.edit",
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];

// Human readable label for every permission key
export const PERMISSION_LABELS: Record<PermissionKey, string> = {
  "analytics.dashboard": "View Dashboard",
  "analytics.export": "Export Analytics",
  "analytics.reports": "Generate Reports",
  "appointments.view": "View Appointments",
  "appointments.create": "Schedule Appointments",
  "appointments.edit": "Modify Appointments",
  "appointments.delete": "Delete Appointments",
  "appointments.assign": "Assign Staff to Appointments",
  "appointments.reschedule": "Reschedule Appointments",
  "appointments.cancel": "Cancel Appointments",
  "appointments.export": "Export Appointments",
  "patients.view": "View Patients",
  "patients.create": "Create Patients",
  "patients.edit": "Edit Patients",
  "patients.delete": "Delete Patients",
  "patients.export": "Export Patients",
  "billing.view": "View Billing",
  "billing.create": "Create Invoices",
  "billing.edit": "Edit Invoices",
  "billing.delete": "Delete Invoices",
  "billing.export": "Export Billing",
  "medical_records.view": "View Medical Records",
  "medical_records.create": "Add Medical Records",
  "medical_records.edit": "Edit Medical Records",
  "medical_records.delete": "Delete Medical Records",
  "prescriptions.view": "View Prescriptions",
  "prescriptions.create": "Create Prescriptions",
  "prescriptions.edit": "Edit Prescriptions",
  "prescriptions.delete": "Delete Prescriptions",
  "test_reports.view": "View Test Reports",
  "test_reports.create": "Create Test Reports",
  "test_reports.edit": "Edit Test Reports",
  "test_reports.delete": "Delete Test Reports",
  "inventory.view": "View Inventory",
  "inventory.create": "Add Inventory Items",
  "inventory.edit": "Edit Inventory",
  "inventory.delete": "Delete Inventory",
  "staff.view": "View Staff",
  "staff.create": "Add Staff Members",
  "staff.edit": "Edit Staff",
  "staff.delete": "Delete Staff",
  "services.view": "View Services",
  "services.create": "Create Services",
  "services.edit": "Edit Services",
  "services.delete": "Delete Services",
  "departments.view": "View Departments",
  "departments.create": "Create Departments",
  "departments.edit": "Edit Departments",
  "departments.delete": "Delete Departments",
  "settings.view": "View Settings",
  "settings.edit": "Edit Settings",
  "odontogram.view": "View Odontogram",
  "odontogram.create": "Create Odontogram",
  "odontogram.edit": "Edit Odontogram",
};

// Default permissions seeded per role (source of truth for seed script)
export const DEFAULT_ROLE_PERMISSIONS: Record<string, PermissionKey[]> = {
  admin: [...PERMISSION_KEYS],

  doctor: [
    "analytics.dashboard",
    "appointments.view",
    "appointments.create",
    "appointments.edit",
    "appointments.reschedule",
    "appointments.cancel",
    "patients.view",
    "patients.create",
    "patients.edit",
    "medical_records.view",
    "medical_records.create",
    "medical_records.edit",
    "prescriptions.view",
    "prescriptions.create",
    "prescriptions.edit",
    "test_reports.view",
    "test_reports.create",
    "test_reports.edit",
    "odontogram.view",
    "odontogram.create",
    "odontogram.edit",
    "services.view",
    "departments.view",
  ],

  nurse: [
    "appointments.view",
    "appointments.edit",
    "appointments.reschedule",
    "patients.view",
    "patients.edit",
    "medical_records.view",
    "medical_records.create",
    "prescriptions.view",
    "test_reports.view",
    "inventory.view",
    "services.view",
  ],

  receptionist: [
    "analytics.dashboard",
    "appointments.view",
    "appointments.create",
    "appointments.edit",
    "appointments.reschedule",
    "appointments.cancel",
    "appointments.assign",
    "patients.view",
    "patients.create",
    "patients.edit",
    "billing.view",
    "billing.create",
    "billing.edit",
    "services.view",
    "departments.view",
    "staff.view",
  ],
};

// Role display config — badge colors matching CareNova design system
export const ROLE_CONFIG = {
  admin: {
    label: "Administrator",
    shortLabel: "Admin",
    badgeClass:
      "bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900",
  },
  doctor: {
    label: "Doctor",
    shortLabel: "Doctor",
    badgeClass:
      "bg-blue-100 text-blue-800 dark:bg-blue-900/60 dark:text-blue-200",
  },
  nurse: {
    label: "Nurse",
    shortLabel: "Nurse",
    badgeClass:
      "bg-green-100 text-green-800 dark:bg-green-900/60 dark:text-green-200",
  },
  receptionist: {
    label: "Receptionist",
    shortLabel: "Receptionist",
    badgeClass:
      "bg-orange-100 text-orange-800 dark:bg-orange-900/60 dark:text-orange-200",
  },
} as const;

export const ROLES = ["admin", "doctor", "nurse", "receptionist"] as const;
export type Role = (typeof ROLES)[number];
